# Generated by Django 2.1.1 on 2018-09-19 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='created_at',
            new_name='created',
        ),
    ]
